### ISSUE TITLE
fit.py import error

### ISSUE THREAD

**Issue by mayork** [hoburg/gpfit#39] opened 2016-06-04 14:59 UTC
Line 8 of fit.py reads

from gpkit.nomials import Posynomial, Monomial, Constraint, MonoEQConstraint

I'm getting an error that Constraint can't be imported. I'm guessing this has been moved during a gpkit refactor. I edited my local copy only to make line 8 read import gpkit and it works, obviously not a good long term fix.

**Comment by whoburg** [comment] 2016-06-06 03:36
duplicate of #37

**Closed by whoburg** 2016-06-06 03:37 UTC
